CREATE TABLE department (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            name VARCHAR(100) NOT NULL,
                            description VARCHAR(500),
                            established_date DATE NOT NULL,

                            CONSTRAINT uk_department_name UNIQUE (name)
);