CREATE TABLE employee_number_sequence (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                          yyyy_mm VARCHAR(6) NOT NULL,
                                          last_sequence BIGINT NOT NULL DEFAULT 0,

                                          CONSTRAINT uk_employee_number_sequence_yyyy_mm UNIQUE (yyyy_mm),
                                          CONSTRAINT chk_employee_number_sequence_yyyy_mm_length CHECK (LENGTH(yyyy_mm) = 6),
                                          CONSTRAINT chk_employee_number_sequence_last_sequence CHECK (last_sequence >= 0)
);

