CREATE TABLE file_info (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           original_file_name VARCHAR(255) NOT NULL,
                           stored_file_name VARCHAR(255) NOT NULL,
                           content_type VARCHAR(100) NOT NULL,
                           size BIGINT NOT NULL,

                           CONSTRAINT uk_file_info_stored_file_name UNIQUE (stored_file_name),
                           CONSTRAINT chk_file_info_size CHECK (size >= 0)
    );