CREATE TABLE employee (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          department_id BIGINT NOT NULL,
                          profile_image_id BIGINT,

                          name VARCHAR(100) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          employee_number VARCHAR(20) NOT NULL,
                          position VARCHAR(100) NOT NULL,
                          hire_date DATE NOT NULL,
                          status VARCHAR(30) NOT NULL,

                          CONSTRAINT uk_employee_email UNIQUE (email),
                          CONSTRAINT uk_employee_employee_number UNIQUE (employee_number),
                          CONSTRAINT uk_employee_profile_image UNIQUE (profile_image_id),

                          CONSTRAINT fk_employee_department
                              FOREIGN KEY (department_id)
                                  REFERENCES department(id),

                          CONSTRAINT fk_employee_profile_image
                              FOREIGN KEY (profile_image_id)
                                  REFERENCES file_info(id)
);