-- 직원 이력 테이블
CREATE TABLE employee_history (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  type VARCHAR(30) NOT NULL,
                                  employee_number VARCHAR(50) NOT NULL,
                                  memo TEXT,
                                  ip_address VARCHAR(45),
                                  created_at TIMESTAMP NOT NULL
);

-- 직원 이력 상세 테이블
CREATE TABLE employee_history_detail (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         employee_history_id BIGINT NOT NULL,
                                         properties VARCHAR(50) NOT NULL,
                                         before_value TEXT,
                                         after_value TEXT,

                                         CONSTRAINT fk_employee_history_detail_history
                                             FOREIGN KEY (employee_history_id)
                                                 REFERENCES employee_history (id)
);