CREATE TABLE backup_info (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             worker VARCHAR(255) NOT NULL,
                             started_at TIMESTAMP NOT NULL,
                             ended_at TIMESTAMP,

                             status VARCHAR(30) NOT NULL,

                             backup_file_id BIGINT,

                             CONSTRAINT fk_backup_info_backup_file
                                 FOREIGN KEY (backup_file_id)
                                     REFERENCES file_info(id)
);